-- ==========================================
-- MASTER SQL SCRIPT: BIG BRAIN ECOSYSTEM UPDATE
-- ==========================================

-- 1. Create Ticket Comments Table
CREATE TABLE IF NOT EXISTS public.ticket_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id UUID NOT NULL REFERENCES public.client_tickets(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for ticket_comments
ALTER TABLE public.ticket_comments ENABLE ROW LEVEL SECURITY;

-- Policy: Admins can see and create all comments
CREATE POLICY "Admins can view all comments" 
ON public.ticket_comments FOR SELECT 
USING (
  (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin' OR 
  (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

CREATE POLICY "Admins can insert comments" 
ON public.ticket_comments FOR INSERT 
WITH CHECK (
  (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin' OR 
  (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

-- Policy: Clients can see comments on their own tickets
CREATE POLICY "Clients can view comments on their tickets" 
ON public.ticket_comments FOR SELECT 
USING (
  ticket_id IN (
    SELECT id FROM public.client_tickets WHERE client_id = auth.uid()
  )
);

-- Policy: Clients can insert comments on their own tickets
CREATE POLICY "Clients can insert comments on their tickets" 
ON public.ticket_comments FOR INSERT 
WITH CHECK (
  ticket_id IN (
    SELECT id FROM public.client_tickets WHERE client_id = auth.uid()
  )
  AND auth.uid() = user_id
);

-- ------------------------------------------

-- 2. Create File Requests Table
CREATE TABLE IF NOT EXISTS public.file_requests (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    client_tag TEXT NOT NULL,
    message TEXT,
    status TEXT DEFAULT 'pending',
    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for file_requests
ALTER TABLE public.file_requests ENABLE ROW LEVEL SECURITY;

-- Policy: Admins can manage all file requests
CREATE POLICY "Admins can manage all file requests" 
ON public.file_requests FOR ALL 
USING (
  (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin' OR 
  (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

-- Policy: Anyone can SELECT a file request (for the magic link)
CREATE POLICY "Anyone can view a specific file request" 
ON public.file_requests FOR SELECT 
USING (true);

-- Policy: Anyone can UPDATE a file request status (when fulfilled)
CREATE POLICY "Anyone can update a file request status" 
ON public.file_requests FOR UPDATE 
USING (true);

-- ------------------------------------------

-- 3. Storage Policy for Client-Vault (Allow public upload to /requests/ folder)
-- Since we are allowing anyone with the link to upload to the "requests" folder, we need an INSERT policy
CREATE POLICY "Allow public uploads to requests folder"
ON storage.objects FOR INSERT
TO public
WITH CHECK (
  bucket_id = 'client-vault' 
  AND (storage.foldername(name))[2] = 'requests'
);

-- Allow public to insert into vault_files table for requests
CREATE POLICY "Allow public inserts for requested vault_files" 
ON public.vault_files FOR INSERT 
TO public
WITH CHECK (
  folder = 'Requested Files'
);
